# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffc182538ed1226771392c93e701db0db1b7d82389eb82671bddd2cd7b5a0061cfb47464e87b6ac0d7affcfcdac9e73da44aae5286aad7ff659d7db94a5fc654

test:
  secret_key_base: 54dd592a7a33d98903847d8222d0353b1a7c71c2deb7834d607b94dccae1b97aaae73558628d750e0525f06085510267e3be28ad1e7ba680a8b4c5eb0b82fa5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
